x-environment:
  &default-env
  ENVIRONMENT: development
  DEBUG: "true"
  LOG_LEVEL: DEBUG
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "uvicorn", "app.presentation.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      <<: *default-env
      TEST_MODE: "true"
    volumes:
      - ./app:/app/app
      - ./tests:/app/testsИсправь
      
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugging
    depends_on:
      - redis
    networks:
      - notification-net
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "celery", "-A", "app.infrastructure.celery_config:celery_app", "worker", "--loglevel=info", "--concurrency=4"]
    environment:
      <<: *default-env
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
    networks:
      - notification-net
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "celery", "-A", "app.infrastructure.celery_config:celery_app", "beat", "--loglevel=info", "--schedule=/tmp/celerybeat-schedule"]
    environment:
      <<: *default-env
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
    networks:
      - notification-net
    restart: always

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "celery", "-A", "app.infrastructure.celery_config:celery_app", "flower", "--port=5555"]
    environment:
      <<: *default-env
      FLOWER_UNAUTHENTICATED_API: "true"
    volumes:
      - ./app:/app/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - notification-net
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - notification-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["python", "-m", "app.presentation.cli", "server", "start", "--host", "0.0.0.0", "--port", "8001"]
  #   environment:
  #     <<: *default-env
  #   volumes:
  #     - ./app:/app/app
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - redis
  #   networks:
  #     - notification-net
  #   restart: always

volumes:
  redis_data:

networks:
  notification-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16